services:
  postgres: 
    image: postgres:17-alpine
    container_name: TeamUp-db
    ports:
    - 5432:5432
#    volumes:
#    - postgres-data:/var/lib/postgresql/data
    environment:
    - POSTGRES_PASSWORD=teamup
    networks:
    - pg_net
  pgamdmin4:
    image: dpage/pgadmin4:8
    container_name: pgadmin-TeamUp
    ports:
    - 8081:80
    volumes:
    - pgadmin-data:/var/lib/pgadmin
    environment:
    - PGADMIN_DEFAULT_EMAIL=admin@admin.com
    - PGADMIN_DEFAULT_PASSWORD=admin
    networks:
    - pg_net
networks:
  pg_net:
volumes:
  pgadmin-data:
# postgres-data: