// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using REST.Data;

#nullable disable

namespace REST.Migrations
{
    [DbContext(typeof(DataContext))]
    [Migration("20241122160153_UserAndGameId")]
    partial class UserAndGameId
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.10")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("REST.Models.Classes.Game", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));
                    NpgsqlPropertyBuilderExtensions.HasIdentityOptions(b.Property<int>("Id"), 3L, null, null, null, null, null);

                    b.Property<string>("Name")
                        .HasColumnType("text");

                    b.Property<int>("OrganizationId")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.ToTable("Games");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Name = "Bulls vs Lakers",
                            OrganizationId = 1
                        },
                        new
                        {
                            Id = 2,
                            Name = "Celtics vs Spurs",
                            OrganizationId = 1
                        });
                });

            modelBuilder.Entity("REST.Models.Classes.Organization", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.ToTable("Organization");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Name = "Group 1"
                        },
                        new
                        {
                            Id = 2,
                            Name = "Group 2"
                        });
                });

            modelBuilder.Entity("REST.Models.Classes.Player", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));
                    NpgsqlPropertyBuilderExtensions.HasIdentityOptions(b.Property<int>("Id"), 8L, null, null, null, null, null);

                    b.Property<string>("Name")
                        .HasColumnType("text");

                    b.Property<int>("OrganizationId")
                        .HasColumnType("integer");

                    b.Property<int>("Points")
                        .HasColumnType("integer");

                    b.Property<int?>("TeamId")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("TeamId");

                    b.ToTable("Players");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Name = "Michael Jordan",
                            OrganizationId = 1,
                            Points = 32292,
                            TeamId = 1
                        },
                        new
                        {
                            Id = 2,
                            Name = "LeBron James",
                            OrganizationId = 1,
                            Points = 35367,
                            TeamId = 2
                        },
                        new
                        {
                            Id = 3,
                            Name = "Kobe Bryant",
                            OrganizationId = 1,
                            Points = 33643,
                            TeamId = 2
                        },
                        new
                        {
                            Id = 4,
                            Name = "Magic Johnson",
                            OrganizationId = 1,
                            Points = 17707,
                            TeamId = 2
                        },
                        new
                        {
                            Id = 5,
                            Name = "Larry Bird",
                            OrganizationId = 1,
                            Points = 21791,
                            TeamId = 3
                        },
                        new
                        {
                            Id = 6,
                            Name = "Kawhi Leonard",
                            OrganizationId = 1,
                            Points = 13937,
                            TeamId = 4
                        },
                        new
                        {
                            Id = 7,
                            Name = "Victor Wembanyama",
                            OrganizationId = 1,
                            Points = 1522,
                            TeamId = 4
                        });
                });

            modelBuilder.Entity("REST.Models.Classes.Team", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));
                    NpgsqlPropertyBuilderExtensions.HasIdentityOptions(b.Property<int>("Id"), 6L, null, null, null, null, null);

                    b.Property<int?>("GameId")
                        .HasColumnType("integer");

                    b.Property<string>("Name")
                        .HasColumnType("text");

                    b.Property<int>("OrganizationId")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("GameId");

                    b.ToTable("Teams");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            GameId = 1,
                            Name = "Bulls",
                            OrganizationId = 1
                        },
                        new
                        {
                            Id = 2,
                            GameId = 1,
                            Name = "Lakers",
                            OrganizationId = 1
                        },
                        new
                        {
                            Id = 3,
                            GameId = 2,
                            Name = "Celtics",
                            OrganizationId = 1
                        },
                        new
                        {
                            Id = 4,
                            GameId = 2,
                            Name = "Spurs",
                            OrganizationId = 1
                        });
                });

            modelBuilder.Entity("REST.Models.Classes.User", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int>("OrganizationId")
                        .HasColumnType("integer");

                    b.Property<string>("Password")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Username")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.ToTable("UserList");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            OrganizationId = 1,
                            Password = "St9tpNN2zrinRGNUgKWCy4JjZRFEorSQ0Zg3a/8m7k4=",
                            Username = "test1"
                        });
                });

            modelBuilder.Entity("REST.Models.Classes.Player", b =>
                {
                    b.HasOne("REST.Models.Classes.Team", "Team")
                        .WithMany("Members")
                        .HasForeignKey("TeamId");

                    b.Navigation("Team");
                });

            modelBuilder.Entity("REST.Models.Classes.Team", b =>
                {
                    b.HasOne("REST.Models.Classes.Game", "Game")
                        .WithMany("Teams")
                        .HasForeignKey("GameId");

                    b.Navigation("Game");
                });

            modelBuilder.Entity("REST.Models.Classes.Game", b =>
                {
                    b.Navigation("Teams");
                });

            modelBuilder.Entity("REST.Models.Classes.Team", b =>
                {
                    b.Navigation("Members");
                });
#pragma warning restore 612, 618
        }
    }
}
